language: cpp
compiler:
  - clang
  - gcc
# command to run tests
script: 
  - git submodule update --init
  - mkdir build
  - cd build
  - cmake .. -DNISTFIT_EXAMPLES=ON -DCMAKE_VERBOSE_MAKEFILE=ON
  - cmake --build . --config Release
  - ./simple

notifications:
  email:
    recipients:
      - ian.bell@nist.gov
    on_success: never # default: change
    on_failure: always # default: always